### ISSUE TITLE
Block sponsored segments

### ISSUE THREAD

**Issue by Kekun** [naipotato/Replay#38]
Many YouTube videos have embeded advertisement segments, the SponsorBlock list them as well as many other kind of segments to automatically skip them, maybe once the app works you can implement it?

https://github.com/ajayyy/SponsorBlock

**Comment by nahuelwexd** [comment]
Uhm, I wasn't aware of this tool, but yes, I'll see to add support once the app works

PS: I had no idea that users could add labels and assign people when opening an issue :thinking:

**Comment by Kekun** [comment]
I didn't add the label nor assigned anybody, that was automatic and I wasn't able to change that. :/

**Comment by nahuelwexd** [comment]
Oh, then it was 'cause you used the "bug report" template instead of starting a new blank issue.

**Comment by ThatOneCalculator** [comment]
+1 on this, most third party YouTube clients use the sponsorblock api at this point
