### ISSUE TITLE
Extend scope beyond youtube, support alternatives (for e.g. Odysee.com, Bitchute.com, PeerTube)

### ISSUE THREAD

**Issue by tutitau** [naipotato/Replay#76]
something similar in newpipe
![newpipe](https://user-images.githubusercontent.com/68787049/111037606-c391e000-841c-11eb-9cf2-a30b86e8358f.png)

**Comment by nahuelwexd** [comment]
I had in mind to do it at some point, but thanks for opening the issue :)
