### ISSUE TITLE
Link subscribed channels across backends (youtube, odysee...) in one place

### ISSUE THREAD

**Issue by tutitau** [naipotato/Replay#77]
Depends on #76

**Is your feature request related to a problem? Please describe.**
Some content creators upload on multiple platforms, some videos are exclusive to one platform and some are duplicated. This makes it really hard (annoying/inconvenient) to keep track of all content from that creator.

**Describe the solution you'd like**
When the feed gets pulled, query all available (and user enabled) backends at the same time. 
The default subscription view should be platform agnostic, zipping all duplicates into one and adding the exclusives. The user shouldn't care where the content is coming from, just that there is content. Basically an abstraction over backends :)
Linking could be done automatically by searching the channel name, but there should be a manual way to do it by channel url in case it fails. 
If a video is available on multiple platforms the user needs a way to rank backends to decide from where we stream the video, or we could just default to youtube. 
It should also have a manual choice in the video card menu.
![grid](https://user-images.githubusercontent.com/68787049/111038769-9811f400-8422-11eb-8e17-1ed14e03b730.png)
the Youtube, Odysee, Bitchute... would be a scrollable menu

**Comment by nahuelwexd** [comment]
I like how this sounds 🤔️

Indeed I think it is something desirable once multiple backends are available, although I hope that linking the videos by title is not something that tends to fail.

[PeerTubeify](https://gitlab.com/Cha_deL/peertubeify) seems to be doing the same
